### ISSUE TITLE
AILL/CERN: Implement the Inivitation Workflow in Reva

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#24]
Based on:
https://github.com/GEANT/OCM-API/pull/39

Add the necessary methods to the OCM http service.

Subtasks
- [x] Add accept endpoint https://github.com/sciencemesh/sciencemesh/issues/36
- [x] Add forward endpoint https://github.com/sciencemesh/sciencemesh/issues/35
- [x] Add generate token endpoint https://github.com/sciencemesh/sciencemesh/issues/37
